### PR TITLE
Refactored CustomCryptoProvider

### PR DESCRIPTION
**Pull request by abatishchev**
Converted most of methods to one-liners

### CODE REVIEW

**Comment by scottbrady91** [comment]
Thanks for the PR, but this repository aims to offer functioning samples to accompany their associated articles. The code should be identical to what is in the article.

In my opinion, updating the example code and article to use extra methods and one-liners doesn't improve the story in the article: https://www.scottbrady91.com/C-Sharp/Supporting-Custom-JWT-Signing-Algorithms-in-dotnet-Core

**Comment by abatishchev** [comment]
The main purpose of the changes was not having one-liners but have better code. Yours is not. It isn't efficient where it could be, neither it does implement the interface property where it could.
The argument to do not update the code in the repo because of the code is the article is a strange argument. What prevents you from updating the article as well?
It's not necessary to take the PR as is but the intend was to show where your code can be improved. Right not it's messy and and bulky but the choice of course is yours.

**Comment by scottbrady91** [comment]
Dude, I'm sorry if you took offence. I just don't see it improving the story.

**Comment by abatishchev** [comment]
No offense. Simple suggestion of a refactoring of the code in an article I actually read and liked :)
It might not be very useful for the readers, intend to agree. If you looked at the diff and got few of my points - then my goal is achieved.
Cheers!

**Pull request closed without merging**
